import pandas as pd
import yfinance as yf
import time
import os
from datetime import datetime

# ------------------------------------------------------------------
# CLASSIFICATION DES TICKERS (à étendre jusqu'à 1800)
# Format : "ticker" : ("classe_d_actif", "bourse")
# Classes : Action, ETF, Obligation, Forex, Indice, MatierePremiere, Crypto, Future
# Bourses : NYSE, NASDAQ, SHANGHAI, TOKYO, EURONEXT, HONGKONG, LONDON, SHENZHEN
# ------------------------------------------------------------------

CLASSIFICATION = {
    # ----- Actions NYSE & NASDAQ (exemples) -----
    "AAPL":   ("Action", "NASDAQ"),
    "MSFT":   ("Action", "NASDAQ"),
    "GOOGL":  ("Action", "NASDAQ"),
    "AMZN":   ("Action", "NASDAQ"),
    "META":   ("Action", "NASDAQ"),
    "TSLA":   ("Action", "NASDAQ"),
    "NVDA":   ("Action", "NASDAQ"),
    "JPM":    ("Action", "NYSE"),
    "JNJ":    ("Action", "NYSE"),
    "V":      ("Action", "NYSE"),
    "WMT":    ("Action", "NYSE"),
    "PG":     ("Action", "NYSE"),
    "UNH":    ("Action", "NYSE"),
    "HD":     ("Action", "NYSE"),
    "DIS":    ("Action", "NYSE"),
    "NFLX":   ("Action", "NASDAQ"),
    "ADBE":   ("Action", "NASDAQ"),
    "CRM":    ("Action", "NYSE"),
    "AMD":    ("Action", "NASDAQ"),
    "INTC":   ("Action", "NASDAQ"),
    "CSCO":   ("Action", "NASDAQ"),
    "IBM":    ("Action", "NYSE"),
    "ORCL":   ("Action", "NYSE"),
    "KO":     ("Action", "NYSE"),
    "PEP":    ("Action", "NASDAQ"),
    "COST":   ("Action", "NASDAQ"),
    "CVX":    ("Action", "NYSE"),
    "XOM":    ("Action", "NYSE"),
    "BAC":    ("Action", "NYSE"),
    "WFC":    ("Action", "NYSE"),
    "C":      ("Action", "NYSE"),
    "GS":     ("Action", "NYSE"),
    "MS":     ("Action", "NYSE"),
    "AXP":    ("Action", "NYSE"),
    "CAT":    ("Action", "NYSE"),
    "GE":     ("Action", "NYSE"),
    "BA":     ("Action", "NYSE"),
    "MMM":    ("Action", "NYSE"),
    "HON":    ("Action", "NASDAQ"),
    "UPS":    ("Action", "NYSE"),
    "FDX":    ("Action", "NYSE"),
    "NKE":    ("Action", "NYSE"),
    "SBUX":   ("Action", "NASDAQ"),
    "MCD":    ("Action", "NYSE"),
    "CMCSA":  ("Action", "NASDAQ"),
    "T":      ("Action", "NYSE"),
    "VZ":     ("Action", "NYSE"),
    "TMUS":   ("Action", "NASDAQ"),
    "ABT":    ("Action", "NYSE"),
    "TMO":    ("Action", "NYSE"),
    "MRK":    ("Action", "NYSE"),
    "PFE":    ("Action", "NYSE"),
    "ABBV":   ("Action", "NYSE"),
    "LLY":    ("Action", "NYSE"),
    "BMY":    ("Action", "NYSE"),
    "GILD":   ("Action", "NASDAQ"),
    "REGN":   ("Action", "NASDAQ"),
    "VRTX":   ("Action", "NASDAQ"),
    "SPGI":   ("Action", "NYSE"),
    "BLK":    ("Action", "NYSE"),
    "SCHW":   ("Action", "NYSE"),
    "ICE":    ("Action", "NYSE"),
    "DE":     ("Action", "NYSE"),
    "LMT":    ("Action", "NYSE"),
    "NOC":    ("Action", "NYSE"),
    "RTX":    ("Action", "NYSE"),
    "GD":     ("Action", "NYSE"),
    "LHX":    ("Action", "NYSE"),
    "ADP":    ("Action", "NASDAQ"),
    "PAYX":   ("Action", "NASDAQ"),
    "CTSH":   ("Action", "NASDAQ"),
    "IT":     ("Action", "NYSE"),
    "AON":    ("Action", "NYSE"),
    "MMC":    ("Action", "NYSE"),
    "ZTS":    ("Action", "NYSE"),
    "EW":     ("Action", "NYSE"),
    "ISRG":   ("Action", "NASDAQ"),
    "SYK":    ("Action", "NYSE"),
    "MDT":    ("Action", "NYSE"),
    "BSX":    ("Action", "NYSE"),
    "ALGN":   ("Action", "NASDAQ"),
    "IDXX":   ("Action", "NASDAQ"),
    "CHTR":   ("Action", "NASDAQ"),
    "ROP":    ("Action", "NASDAQ"),
    "SHW":    ("Action", "NYSE"),
    "PPG":    ("Action", "NYSE"),
    "ECL":    ("Action", "NYSE"),
    "APD":    ("Action", "NYSE"),
    "LIN":    ("Action", "NYSE"),
    "DOW":    ("Action", "NYSE"),
    "DD":     ("Action", "NYSE"),
    "FCX":    ("Action", "NYSE"),
    "NEM":    ("Action", "NYSE"),
    "GDX":    ("Action", "NYSE"),
    "PLTR":   ("Action", "NYSE"),
    "SNOW":   ("Action", "NYSE"),
    "DDOG":   ("Action", "NASDAQ"),
    "NET":    ("Action", "NYSE"),
    "UBER":   ("Action", "NYSE"),
    "LYFT":   ("Action", "NASDAQ"),
    "ABNB":   ("Action", "NASDAQ"),
    "RBLX":   ("Action", "NYSE"),
    "COIN":   ("Action", "NASDAQ"),
    "SQ":     ("Action", "NYSE"),
    "PYPL":   ("Action", "NASDAQ"),
    "SHOP":   ("Action", "NYSE"),
    "SPOT":   ("Action", "NYSE"),
    "ROKU":   ("Action", "NASDAQ"),
    "TTD":    ("Action", "NASDAQ"),
    "ZS":     ("Action", "NASDAQ"),
    "MRNA":   ("Action", "NASDAQ"),
    "BIIB":   ("Action", "NASDAQ"),
    "ILMN":   ("Action", "NASDAQ"),
    "WBA":    ("Action", "NASDAQ"),
    "NIO":    ("Action", "NASDAQ"),
    "RKLB":   ("Action", "NYSE"),
    "SOFI":   ("Action", "NASDAQ"),
    "JOBY":   ("Action", "NYSE"),

    # ----- ETF (bourses variées) -----
    "SPY":    ("ETF", "NYSE"),
    "QQQ":    ("ETF", "NASDAQ"),
    "GLD":    ("ETF", "NYSE"),
    "IVV":    ("ETF", "NYSE"),
    "VOO":    ("ETF", "NYSE"),
    "VTI":    ("ETF", "NYSE"),
    "VT":     ("ETF", "NYSE"),
    "BND":    ("ETF", "NASDAQ"),
    "AGG":    ("ETF", "NYSE"),
    "TLT":    ("ETF", "NASDAQ"),
    "IEF":    ("ETF", "NASDAQ"),
    "LQD":    ("ETF", "NYSE"),
    "HYG":    ("ETF", "NYSE"),
    "EEM":    ("ETF", "NYSE"),
    "VWO":    ("ETF", "NYSE"),
    "EWZ":    ("ETF", "NYSE"),
    "FXI":    ("ETF", "NYSE"),
    "EFA":    ("ETF", "NYSE"),
    "VGK":    ("ETF", "NYSE"),
    "INDA":   ("ETF", "NASDAQ"),
    "ARKK":   ("ETF", "NYSE"),
    "ARKW":   ("ETF", "NYSE"),
    "QCLN":   ("ETF", "NASDAQ"),
    "ICLN":   ("ETF", "NASDAQ"),
    "XLE":    ("ETF", "NYSE"),
    "XLF":    ("ETF", "NYSE"),
    "XLK":    ("ETF", "NYSE"),
    "XLV":    ("ETF", "NYSE"),
    "XLI":    ("ETF", "NYSE"),
    "XLY":    ("ETF", "NYSE"),
    "XLP":    ("ETF", "NYSE"),
    "XLU":    ("ETF", "NYSE"),
    "IBB":    ("ETF", "NASDAQ"),
    "XBI":    ("ETF", "NYSE"),
    "SMH":    ("ETF", "NASDAQ"),
    "SOXX":   ("ETF", "NASDAQ"),
    "VTWO":   ("ETF", "NASDAQ"),
    "IWM":    ("ETF", "NYSE"),
    "IJH":    ("ETF", "NYSE"),
    "IJR":    ("ETF", "NYSE"),
    "EZA":    ("ETF", "NYSE"),
    "AFK":    ("ETF", "NYSE"),
    "NGE":    ("ETF", "NYSE"),

    # ----- Obligations -----
    "TLT":    ("Obligation", "NASDAQ"),
    "IEF":    ("Obligation", "NASDAQ"),
    "SHY":    ("Obligation", "NASDAQ"),
    "BND":    ("Obligation", "NASDAQ"),
    "AGG":    ("Obligation", "NYSE"),

    # ----- Forex -----
    "EURUSD=X": ("Forex", "FOREX"),
    "GBPUSD=X": ("Forex", "FOREX"),
    "USDJPY=X": ("Forex", "FOREX"),
    "USDCHF=X": ("Forex", "FOREX"),
    "AUDUSD=X": ("Forex", "FOREX"),
    "USDCAD=X": ("Forex", "FOREX"),
    "NZDUSD=X": ("Forex", "FOREX"),
    "EURGBP=X": ("Forex", "FOREX"),
    "EURJPY=X": ("Forex", "FOREX"),
    "GBPJPY=X": ("Forex", "FOREX"),
    "AUDJPY=X": ("Forex", "FOREX"),
    "CADJPY=X": ("Forex", "FOREX"),
    "CHFJPY=X": ("Forex", "FOREX"),
    "EURCHF=X": ("Forex", "FOREX"),
    "GBPCHF=X": ("Forex", "FOREX"),

    # ----- Matières premières -----
    "GC=F":   ("MatierePremiere", "COMMODITY"),
    "SI=F":   ("MatierePremiere", "COMMODITY"),
    "CL=F":   ("MatierePremiere", "COMMODITY"),
    "NG=F":   ("MatierePremiere", "COMMODITY"),
    "HO=F":   ("MatierePremiere", "COMMODITY"),
    "RB=F":   ("MatierePremiere", "COMMODITY"),
    "ZW=F":   ("MatierePremiere", "COMMODITY"),
    "ZC=F":   ("MatierePremiere", "COMMODITY"),

    # ----- Crypto-monnaies -----
    "BTC-USD":  ("Crypto", "CRYPTO"),
    "ETH-USD":  ("Crypto", "CRYPTO"),
    "BNB-USD":  ("Crypto", "CRYPTO"),
    "SOL-USD":  ("Crypto", "CRYPTO"),
    "ADA-USD":  ("Crypto", "CRYPTO"),
    "XRP-USD":  ("Crypto", "CRYPTO"),
    "DOGE-USD": ("Crypto", "CRYPTO"),
    "DOT-USD":  ("Crypto", "CRYPTO"),
    "AVAX-USD": ("Crypto", "CRYPTO"),
    "MATIC-USD":("Crypto", "CRYPTO"),
    "LINK-USD": ("Crypto", "CRYPTO"),
    "LTC-USD":  ("Crypto", "CRYPTO"),
    "BCH-USD":  ("Crypto", "CRYPTO"),
    "UNI-USD":  ("Crypto", "CRYPTO"),
    "ATOM-USD": ("Crypto", "CRYPTO"),
    "APE-USD":  ("Crypto", "CRYPTO"),
    "NEAR-USD": ("Crypto", "CRYPTO"),
    "ALGO-USD": ("Crypto", "CRYPTO"),
    "VET-USD":  ("Crypto", "CRYPTO"),
    "FIL-USD":  ("Crypto", "CRYPTO"),
    "ICP-USD":  ("Crypto", "CRYPTO"),
    "ETC-USD":  ("Crypto", "CRYPTO"),
    "XLM-USD":  ("Crypto", "CRYPTO"),
    "HBAR-USD": ("Crypto", "CRYPTO"),
    "FTM-USD":  ("Crypto", "CRYPTO"),
    "MANA-USD": ("Crypto", "CRYPTO"),
    "SAND-USD": ("Crypto", "CRYPTO"),
    "GALA-USD": ("Crypto", "CRYPTO"),
    "AAVE-USD": ("Crypto", "CRYPTO"),
    "CRV-USD":  ("Crypto", "CRYPTO"),
    "MKR-USD":  ("Crypto", "CRYPTO"),
    "COMP-USD": ("Crypto", "CRYPTO"),
    "ZEC-USD":  ("Crypto", "CRYPTO"),
    "DASH-USD": ("Crypto", "CRYPTO"),
    "XTZ-USD":  ("Crypto", "CRYPTO"),
    "EOS-USD":  ("Crypto", "CRYPTO"),
    "NEO-USD":  ("Crypto", "CRYPTO"),
    "IOTA-USD": ("Crypto", "CRYPTO"),
    "THETA-USD":("Crypto", "CRYPTO"),
    "KSM-USD":  ("Crypto", "CRYPTO"),
    "WAVES-USD":("Crypto", "CRYPTO"),
    "ZIL-USD":  ("Crypto", "CRYPTO"),
    "QTUM-USD": ("Crypto", "CRYPTO"),
    "RVN-USD":  ("Crypto", "CRYPTO"),
    "SC-USD":   ("Crypto", "CRYPTO"),
    "OMG-USD":  ("Crypto", "CRYPTO"),
    "LSK-USD":  ("Crypto", "CRYPTO"),
    "DCR-USD":  ("Crypto", "CRYPTO"),
    "AR-USD":   ("Crypto", "CRYPTO"),
    "HNT-USD":  ("Crypto", "CRYPTO"),
    "FLOW-USD": ("Crypto", "CRYPTO"),
    "MINA-USD": ("Crypto", "CRYPTO"),
    "CHZ-USD":  ("Crypto", "CRYPTO"),
    "ENJ-USD":  ("Crypto", "CRYPTO"),
    "BAT-USD":  ("Crypto", "CRYPTO"),
    "KAVA-USD": ("Crypto", "CRYPTO"),
    "LUNA-USD": ("Crypto", "CRYPTO"),
    "UST-USD":  ("Crypto", "CRYPTO"),
    "CELO-USD": ("Crypto", "CRYPTO"),
    "ONE-USD":  ("Crypto", "CRYPTO"),
    "KDA-USD":  ("Crypto", "CRYPTO"),
    "RUNE-USD": ("Crypto", "CRYPTO"),
    "TLM-USD":  ("Crypto", "CRYPTO"),
    "AXS-USD":  ("Crypto", "CRYPTO"),
    "SLP-USD":  ("Crypto", "CRYPTO"),
    "YFI-USD":  ("Crypto", "CRYPTO"),
    "SNX-USD":  ("Crypto", "CRYPTO"),
    "SUSHI-USD":("Crypto", "CRYPTO"),
    "UMA-USD":  ("Crypto", "CRYPTO"),
    "REN-USD":  ("Crypto", "CRYPTO"),
    "BNT-USD":  ("Crypto", "CRYPTO"),
    "LRC-USD":  ("Crypto", "CRYPTO"),
    "ZRX-USD":  ("Crypto", "CRYPTO"),
    "OCEAN-USD":("Crypto", "CRYPTO"),
    "FET-USD":  ("Crypto", "CRYPTO"),
    "AGIX-USD": ("Crypto", "CRYPTO"),
    "OCEAN-USD":("Crypto", "CRYPTO"),
    "FET-USD":  ("Crypto", "CRYPTO"),
    "AGIX-USD": ("Crypto", "CRYPTO"),

    # ----- Futures (exemples) -----
    "ES=F":   ("Future", "CME"),
    "NQ=F":   ("Future", "CME"),
    "YM=F":   ("Future", "CME"),
    "RTY=F":  ("Future", "CME"),
    "ZN=F":   ("Future", "CBOT"),
    "ZB=F":   ("Future", "CBOT"),
    "ZF=F":   ("Future", "CBOT"),
    "ZT=F":   ("Future", "CBOT"),
    "HE=F":   ("Future", "CME"),
    "LE=F":   ("Future", "CME"),
    "GF=F":   ("Future", "CME"),
    "ZS=F":   ("Future", "CBOT"),
    "ZW=F":   ("Future", "CBOT"),
    "ZC=F":   ("Future", "CBOT"),
    "ZM=F":   ("Future", "CBOT"),
    "CL=F":   ("Future", "NYMEX"),
    "NG=F":   ("Future", "NYMEX"),
    "HO=F":   ("Future", "NYMEX"),
    "RB=F":   ("Future", "NYMEX"),
    "GC=F":   ("Future", "COMEX"),
    "SI=F":   ("Future", "COMEX"),
    "HG=F":   ("Future", "COMEX"),
    "PL=F":   ("Future", "NYMEX"),
    "PA=F":   ("Future", "NYMEX"),
}

# Construire la liste TICKERS à partir des clés du dictionnaire
TICKERS = list(CLASSIFICATION.keys())

# ------------------------------------------------------------------
# FONCTION DE RÉCUPÉRATION AVEC CLASSIFICATION
# ------------------------------------------------------------------
def fetch_ticker_data(ticker):
    try:
        t = yf.Ticker(ticker)
        info = t.info
        hist = t.history(period="3mo", interval="1d")
        if hist.empty:
            return None
        price = info.get("currentPrice") or info.get("regularMarketPrice") or hist["Close"].iloc[-1]
        asset_class, exchange = CLASSIFICATION.get(ticker, ("Action", "AUTRE"))
        return {
            "ticker": ticker,
            "name": info.get("shortName", ticker),
            "price": price,
            "pe": info.get("trailingPE"),
            "pb": info.get("priceToBook"),
            "roe": info.get("returnOnEquity"),
            "debt_eq": info.get("debtToEquity"),
            "fcf": info.get("freeCashflow"),
            "eps": info.get("trailingEps"),
            "bvps": info.get("bookValue"),
            "ev_ebitda": info.get("enterpriseToEbitda"),
            "market_cap": info.get("marketCap"),
            "sector": info.get("sector", "—"),
            "currency": info.get("currency", "USD"),
            "asset_class": asset_class,
            "exchange": exchange,
            "rsi": 50,            # à calculer plus tard
            "momentum_1m": 0,
            "momentum_3m": 0,
            "volatility": 0,
            "drawdown": 0,
            "hist_closes": hist["Close"].tail(60).tolist(),
            "hist_dates": [str(d.date()) for d in hist["Close"].tail(60).index],
        }
    except Exception as e:
        print(f"Erreur sur {ticker}: {e}")
        return None

# ------------------------------------------------------------------
# MAIN
# ------------------------------------------------------------------
def main():
    print(f"Début de la collecte - {datetime.now()}")
    results = []
    total = len(TICKERS)
    for i, ticker in enumerate(TICKERS, 1):
        print(f"[{i}/{total}] Traitement de {ticker}...")
        data = fetch_ticker_data(ticker)
        if data:
            results.append(data)
        time.sleep(1.0)
    df = pd.DataFrame(results)
    os.makedirs("data", exist_ok=True)
    df.to_parquet("data/latest.parquet", index=False)
    print(f"Terminé. {len(results)} actifs sauvegardés.")

if __name__ == "__main__":
    main()